### ISSUE TITLE
[R6] Monitor has a few issues

### ISSUE THREAD

**Issue by CaptainAmpersand** [VolmitSoftware/React#170]
http://i.nanonuke.net/2018-02-21_01-46-53-0.gif

It just looks weird right now, no errors, just... Adamant about those numbers (lol)

React ver 6.0.51
Spigot v 1.12.2

**Comment by cyberpwnn** [comment]
There arent any good ways to fix that
1. The text is centered meaning spaces on the left and right (to force center it) wouldnt work since it isnt MONOSPACED
2. People have texture packs -> You do in this example 
3. Force centering it would work for default, but would make it wiggle even worse if you have a pack on

A few things i DO actually do to prevent too much shaking though
1. Decimal points should only show if it usually doesnt (.... to prevent flickering of 0.43 and back to 1)
2. If it always shows a decimal, force show .0 when it is 5 -> 5.0 to prevent char changes
