### ISSUE TITLE
Add a PingKicker

### ISSUE THREAD

**Issue by lucas2107** [VolmitSoftware/React#228]
Add a ping kicker. High ping players are annoying on PvP servers

Functions:
* Player must be logged in for 1 minute before checks start
* Warn players if they have a high ping
* Kick Player if him ping is higher than X ms the last minute

**Comment by lucas2107** [comment]
React is checking players ping and it's not used atm ^^

**Comment by lucas2107** [comment]
@master4life And? It's a feature, React is monitoring player ping, this will be helpful for some servers.

**Comment by cyberpwnn** [comment]
@master4life a boolean option to turn it on isnt bloat :P Nothing would be activated and no memory would be used by default if its off (thanks to react services). I will add it, but as you are correct (being that it isnt essential for react) it may be a while before it's implemented.

@Frerduro so you cant stay on my server and lag out all the time because your internet sucks

**Comment by cyberpwnn** [comment]
Lower ping players doesnt cause any lag at all, in fact the server can be a bit lazier with them. If you need it for some other reason such as pvp or something, react wouldn't be the place for this as it doesn't actively check ping fast enough for this.
