### ISSUE TITLE
Shearing sheeps

### ISSUE THREAD

**Issue by AzDreamerr** [VolmitSoftware/React#261]
Hello!
When sheep is stacked (x4 for example) and i shearing sheep drop isn't x4, but like for one sheep.

**Comment by cyberpwnn** [comment]
Wouldnt this not be good? Stack 12 sheeps of white, and make them merge with a pink sheep to get 13x pink then shear it to get 13x pink wool, then just wait for it to feed again?

I see several issues either way with this.

### Option 1: Change Nothing
It is theoretically possible to get MORE of a certain colored wool you want by trying over and over to get the stack of some color then dumping in more sheep, then repeat-killing it down to it's last life to get max colored wool

### Option 2: Make it so sheep shear multiples of the stack
By doing this, the above option would still happen, just would make it easier to do. It would also mean you would get more wool faster due to how often sheep can eat. Perhaps a config option for this maybe?

### Option 3: Make sheep spawn with wool each time the next life is killed
This would allow multiple shears, and prevent getting high wool counts as fast, but it also creates a direct dupe in the sense that putting that sheared sheep into a stack, then killing the sheared stack would allow you to re-grow sheep by command. 

Interesting lol, i diddnt realize sheep entity stacks can be duped in so many ways lol. Im thinking keep option 1 (do nothing) but add an option to give a multiplied version of the wool when sheared (option 2) in the config.

**Comment by AzDreamerr** [comment]
I think the problem with color wool is not as scary as problem with wool at all.

**Comment by cyberpwnn** [comment]
Ill go with option 1 and add option 2 in the config then

**Comment by cyberpwnn** [comment]
Issue merge #352
