### ISSUE TITLE
Server Lock/Lag after exactly 7 hours of being up!

### ISSUE THREAD

**Issue by HexedHero** [VolmitSoftware/React#295]
Hey, so I don't know how to even go about this issue, but since I got the new React 6, after my Survival 1 server is online for exactly just over 7 hours the TPS goes to 5-10 and it lags for 5-10 seconds every 5 seconds and is just unplayable and HAS to restart, its ONLY with React but it doesn't do it on the hub or survival 2 maybe since there is a lot less players on them servers.

It does it EXACTLY 7 hours after servers been up, its soo weird. Exact same config as others and same plugins everything. Survival 1 and 2 is a 1:1 copy apart from the world size that's it.

**Comment by HexedHero** [comment]
Update: Survival 2 is DOING IT AS WELL, But a little different the TPS is still 19-20 because there is only like 5-15 players on that server but the freezing of the server is there!

**Comment by HexedHero** [comment]
Update 2: The freezing happens EXACTLY when React does Purge chunks, guessing its unstable af when the servers been up for ages, prob explains the TPS too, since my TPS is an avg the last minute.
https://i.gyazo.com/99e686770f63a1033ff20323b456a5f1.png

**Comment by lucas2107** [comment]
Please provide us timings

**Comment by cyberpwnn** [comment]
For now, set purge-enabled: false in the config.yml

My guess is your server has a lot of garbage that hasnt been collected by gc (since nothing is happening) then all of the sudden react wants to purge chunks every so often which can cause a gc spike if you are low on memory. 

But i dont think this is an issue i can fix. You might want to gather more information because all i can tell from what is here, it's gc.

**Comment by HexedHero** [comment]
https://i.gyazo.com/cde21e784019a2d55da35f1678027e64.png
I have purge to false
