### ISSUE TITLE
React fail to cull/purge entities

### ISSUE THREAD

**Issue by lucas2107** [VolmitSoftware/React#301]
React, sometimes, fail to cull/purge entities.

When it's happening, GC up to 1GB/s (instead of 150mb/s)
TPS drop more and more...

When I run /re act cull-entities, it's saying "culling 65 entities types on ... 2.5k chunks" and the other message don't appear

When I run /re act purge-entities, it's saying "purging 0 entities types on 0 chunks"

React version: Latest
Paper 1.8.8

**Comment by cyberpwnn** [comment]
I need to make an action queue status command so you can see if it's running or what it's doing i guess

**Comment by lucas2107** [comment]
http://prntscr.com/j5bo92

**Comment by cyberpwnn** [comment]
Also #305

**Comment by cyberpwnn** [comment]
I cannot seem to reproduce

**Comment by LogGits** [comment]
I am also having this issue. Though purge does remove them.
[![Screenshot from Gyazo](https://gyazo.com/e58e474d5fb951b2c7ecca9b4614a199/raw)](https://gyazo.com/e58e474d5fb951b2c7ecca9b4614a199)

**Comment by cyberpwnn** [comment]
React will report that it culled 0 entities across 0 chunks if there is nothing to cull, since it is following the rules in the config. If it reports back 0, then that means it's keeping entities in check in the first place, and there was no need to manually cull entities in the first place.

As for chunks, it will always return "purged 0 chunks" if
* No one is online and there are literally no chunks loaded, or a plugin prevented the spawn or somewhere else from being unloaded
* Players are online, but there are no chunks OUTSIDE of everyone's view distance that is able to be culled (i.e. not prevented by citizens for example)
