### ISSUE TITLE
Massive chunk issues with React

### ISSUE THREAD

**Issue by Larskei-dev** [VolmitSoftware/React#534]
**Describe the bug**
Ghost chunks and broken chunks appearing everywhere around the map

**To Reproduce**
1. Go to version 1.8.8 Taco/Paper spigot
2. Create a void world with multiverse
3. Do a massive world edit or things like that to make the issue more visible at/near 0 0
4. Relog
5. You should start seeing broken chunks constantly

**Expected behavior**
This happens all over the server, even in areas where no world edits have been made, and commonly at 0 0, but also everywhere else very commonly

**Server and Plugin Informations**
 - Installed plugins: (Did this with FAWE, and WorldEdit, on a clean server, same issues)
 - React Version: 6.617
 - Server Platform and Version [Paper/Tacospigot 1.8.8]:
 - Operating System: Linux 

**Additional context**
There was no console logs to be read, however the problem did lessen its effects when we turned on NMS adapters and turned of Tile Throttling in the worlds config, however it was still extremely bad.

**Comment by relavis** [comment]
This issue has also been confirmed by another user running Windows 10, regular Spigot 1.8.8. Latest 1.8.8 FAWE.
[FAWE version](https://cdn.discordapp.com/attachments/189665083817852928/710764164519559238/unknown.png)
[/re env](https://cdn.discordapp.com/attachments/189665083817852928/710762887047806986/unknown.png)
[Spigot vers](https://cdn.discordapp.com/attachments/189665083817852928/710763037346365490/unknown.png)

**Comment by cyberpwnn** [comment]
Ghost chunks have a lot to do with packets back in 1.8. 1.8 has a loose cache for chunks, and for some reason (usually fawe is the cause here) a packet changes a chunk, the server then updates the chunk, and the client has misinformation. I dont think react is causing it, it just might be creating an environment for it to happen more often. 

What im saying is this is almost impossible to fix because a lot of plugins cause this and its near impossible to find how you are causing a bug in minecraft itself to happen.
