### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by tsao-chi** [VolmitSoftware/React#560]
What is the license of this repo?

**Comment by yeojhenrie** [comment]
i guess it is open source but I can't compile it because of [ERROR] Failed to execute goal on project React: Could not resolve dependencies for project com.volmit:React:jar:6.634: The following artifacts could not be resolved: org.projectlombok:lombok:jar:1.18.8, org.zeroturnaround:zt-zip:jar:1.13: Failure to find org.projectlombok:lombok:jar:1.18.8 in https://hub.spigotmc.org/nexus/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of spigot-repo has elapsed or updates are forced -> [Help 1]                     
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project React: Could not resolve dependencies for project com.volmit:React:jar:6.634: The following artifacts could not be resolved: org.projectlombok:lombok:jar:1.18.8, org.zeroturnaround:zt-zip:jar:1.13: Failure to find org.projectlombok:lombok:jar:1.18.8 in https://hub.spigotmc.org/nexus/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of spigot-repo has elapsed or updates are forced

**Comment by tsao-chi** [comment]
ping @relavis

**Comment by relavis** [comment]
React is licensed under the WTFPL (Do What the Fuck You Want to) public license. Therefore, feel free to do whatever the fuck you want.

For reference: http://www.wtfpl.net/
